FROM python:3.8

WORKDIR /app

ENV  FLASK_APP=app
ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install pipenv

COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

COPY . .

CMD ["python", "flask run"]

